In [42]:
import keras
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
from keras.preprocessing.text import Tokenizer
from keras.datasets import imdb
import numpy as np
import pandas as pd
from keras.utils.np_utils import to_categorical
import re

In [3]:
max_features = 20000
maxlen = 80
batch_size = 32

In [168]:
(x_train,y_train), (x_test, y_test) = imdb.load_data(num_words = max_features) 


In [5]:
word_index = imdb.get_word_index()
index_word = {i: word for word, i in word_index.items()}
index_word[1]

'the'

In [166]:
print([index_word.get(word, ' ') for word in x_test[0]])
print(x_test)

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'the', 'wonder', 'own', 'as', 'by', 'is', 'sequence', 'i', 'i', 'jars', 'roses', 'to', 'of', 'hollywood', 'br', 'of', 'down', 'shouting', 'getting', 'boring', 'of', 'ever', 'it', 'sadly', 'sadly', 'sadly', 'i', 'i', 'was', 'then', 'does', "don't", 'close', 'faint', 'after', 'one', 'carry', 'as', 'by', 'are', 'be', 'favourites', 'all', 'family', 'turn', 'in', 'does', 'as', 'three', 'part', 'in', 'another', 'some', 'to', 'be', 'probably', 'with', 'world', 'uncaring', 'her', 'an', 'have', 'faint', 'beginning', 'own', 'as', 'is', 'sequence']
[[   0    0    0 ...   14    6  717]
 [1669  398  229 ...  125    4 3077]
 [ 687    2  203 ...    9   57  975]
 ...
 [   0    0    0 ...   21  846 5518]
 [   8   97   14 ... 2302    7  470]
 [ 718    2    9 ...   34 2005 2643]]


In [236]:
x_train = sequence.pad_sequences(x_train, maxlen = maxlen)
x_test = sequence.pad_sequences(x_test, maxlen = maxlen)
len(x_train)

25000

In [237]:
Model = Sequential()
Model.add(Embedding(max_features, 128))
Model.add(LSTM(128, dropout = 0.2, recurrent_dropout = 0.2))
Model.add(Dense(1, activation = 'sigmoid'))

In [238]:
Model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [239]:
Model.fit(x_train, y_train,
         batch_size = batch_size,
         epochs = 20,
         validation_data = (x_test, y_test))

Train on 25000 samples, validate on 25000 samples
Epoch 1/20
25000/25000 [==============================] - 94s 4ms/step - loss: 0.4736 - acc: 0.7762 - val_loss: 0.3695 - val_acc: 0.8380
Epoch 2/20
25000/25000 [==============================] - 92s 4ms/step - loss: 0.2972 - acc: 0.8795 - val_loss: 0.3771 - val_acc: 0.8392
Epoch 3/20
25000/25000 [==============================] - 91s 4ms/step - loss: 0.2149 - acc: 0.9181 - val_loss: 0.4208 - val_acc: 0.8349
Epoch 4/20
25000/25000 [==============================] - 93s 4ms/step - loss: 0.1510 - acc: 0.9442 - val_loss: 0.4906 - val_acc: 0.8262
Epoch 5/20
25000/25000 [==============================] - 98s 4ms/step - loss: 0.1137 - acc: 0.9597 - val_loss: 0.5462 - val_acc: 0.8250
Epoch 6/20
25000/25000 [==============================] - 99s 4ms/step - loss: 0.0819 - acc: 0.9712 - val_loss: 0.6087 - val_acc: 0.8242
Epoch 7/20
25000/25000 [==============================] - 98s 4ms/step - loss: 0.0605 - acc: 0.9796 - val_loss: 0.7146 - val_acc

In [240]:
Model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 128)         2560000   
_________________________________________________________________
lstm_4 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 129       
Total params: 2,691,713
Trainable params: 2,691,713
Non-trainable params: 0
_________________________________________________________________


In [151]:
score, accur = Model.evaluate(x_test, y_test, batch_size)

25000/25000 [==============================] - 11s 443us/step


In [152]:
print("score", score)
print("accuracy", accur)

score 0.5527440076255798
accuracy 0.71152


In [ ]:
word_index = imdb.get_word_index()

In [230]:
words = 'nice movie'
words = [words.split()]
words

[['nice', 'movie']]

In [231]:
reveiw = []
for word in words:
    wo = []
    for n in word:
        if n in word_index:
            wo.append(word_index[n])
        else:
            wo.append(0)
    reveiw.append(wo)
    

In [232]:
words = sequence.pad_sequences(reveiw, maxlen=80)
words

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        324,  17]], dtype=int32)

In [233]:
predictions = Model.predict(words, batch_size = None)
predictions

array([[0.9212638]], dtype=float32)